#pragma once

// Worker Thread Event
enum EVENT_TYPE {
	EV_RECV,
	EV_SEND,
	EV_MONSTER_UPDATE,
	EV_NATURAL_UPDATE,
	EV_DB,
	EV_END
};

enum DATABASE_SAVE_TYPE {
	DBS_LOGIN_SUCCESS,
	DBS_LOGIN_FAIL,
	DBS_LOGOUT_SUCCESS,
	DBS_LOGOUT_FAIL,
	DBS_END
};

// DB Process Event
enum class DB_STATE_TYPE
{
	LOGIN,
	LOGOUT,
	GET_ITEM,
	REMOVE_ITEM,
	CHANGE_STATE,
	CHANGE_INVEN,
	END
};

// [About Animal]
enum ANIMAL_TYPE { A_BEAR, A_BOAR, A_DEER, A_WOLF, A_END };
enum BEHAVIOR_TYPE { B_WARLIKE, B_PASSIVE, B_EVASION, B_END };
enum class ANIMAL_STATE_TYPE { ATTACK, FOLLOW, EVASION, IDLE, DIE, RESPAWN, HEAL, END };
enum class ANIMAL_UPDATE_TYPE { ATTACK, FOLLOW, EVASION, IDLE, DIE, RESPAWN, HEAL, DAMAGE, END };
// Natural
enum NATURAL_TYPE {
	NATURAL_TREE,
	NATURAL_STONE,
	NATURAL_BUSH,
	NATURAL_NONE,
	NATURAL_END
};

// Housing
enum HOUSING_TYPE {

	HOUSING_FOUNDATION,
	HOUSING_WALL,
	HOUSING_DOOR,
	HOUSING_WINDOW,
	HOUSING_FLOOR,
	HOUSING_END,
	HOUSING_ETC
};



enum class NATURAL_UPDATE_TYPE
{
	RESPAWN, DAMAGE, END
};

enum class PLAYER_STATE_TYPE {
	IDLE, DIE, END
};

enum DIR_TYPE
{
	RIGHT,
	UP,
	FRONT,
	END
};

enum ITEM_TYPE {
	ITEM_NOTHING = 0,

	ITEM_TOOL,					//======= 도구 =======
	ITEM_PICKAXE,
	ITEM_AXE,
	ITEM_HAMMER,
	ITEM_MACHETTE,
	ITEM_WOODCLUB,
	ITEM_BOW,
	ITEM_CAMPFIRE,
	ITEM_MAP,
	ITEM_TOOL_END,				//======= =======

	ITEM_STUFF = ITEM_TOOL_END, //======= 재료 =======
	ITEM_WOOD,
	ITEM_WOODSTICK,
	ITEM_STONE,
	ITEM_LEATHER,
	ITEM_CLOTH,
	ITEM_BONE,
	ITEM_ARROW,
	ITEM_STUFF_END,				//======= =======

	ITEM_USABLE = ITEM_STUFF_END,	//======= 소모품 =======
	ITEM_FOOD = ITEM_USABLE,		//===== 식량 =====
	ITEM_MEAT,
	ITEM_COOKMEAT,
	ITEM_CHOCOLATEBAR,
	ITEM_CAN,
	ITEM_APPLE,
	ITEM_FOOD_END,					//===== =====
	ITEM_DRINK = ITEM_FOOD_END,		//===== 마실것 =====
	ITEM_EMPTY_BOTTLE,
	ITEM_WATER_BOTTLE,
	ITEM_SODA,
	ITEM_DRINK_END,					//===== =====
	ITEM_HEAL = ITEM_DRINK_END,		//===== 회복 =====
	ITEM_MEDICKIT,
	ITEM_BANDAGE,
	ITEM_HEAL_END,					//===== =====
	ITEM_USABLE_END,				//======= =======

	ITEM_ARMOR = ITEM_USABLE_END,	//======= 방어구(옷) =======
	ITEM_TSHIRT,
	ITEM_SHIRT,
	ITEM_JACKET,
	ITEM_ARMOR_END,					//======= =======

	ITEM_HOUSING = ITEM_ARMOR_END,	//======= 하우징 ========
	ITEM_BLUEPRINT,
	ITEM_HOUSING_END,				//======= ========

	ITEM_END
};